# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}. 
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/

title: Statistics & Machine Learning
subtitle: # site tagline that appears below site title in masthead
email: rahul235@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Statistics & Machine Learning repository. 
twitter_username: tisrahul
github_username: rahul235
minimal_mistakes_skin: "contrast" # default, "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: true
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:                   #need account on algolia to get the below details.
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : 464a18c82e0157714
  instant_search         : true # false (default), true
locale: "en-US" #en-GB, en
#url: "https://rahul235.github.io/"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/
timezone: Asia/Calcutta

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
 exclude:
    - README.md
    - R.md
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Kumar Rahul"
  avatar : "/assets/images/PhotoRahul_new.png"
  bio    : "Passionate about uncovering patterns from data!!!"
  location : "Karnataka, India"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://rahul235.github.io/data2decisions"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/tisrahul/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rahul235/"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_dates: true
      date_format: "%Y-%m-%d"
      read_time: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

theme: minimal-mistakes-jekyll
